-- All IDs are positive cryptographically generated int64 values, never database
-- auto-increment IDs. These portable SQL types work on SQLite and PostgreSQL.
-- Composite tenant foreign keys enforce ownership even if application scope fails.
CREATE TABLE organizations (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 name TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
 timezone TEXT NOT NULL DEFAULT 'UTC',
 quota_json TEXT NOT NULL DEFAULT '{}',
 created_at TIMESTAMP NOT NULL,
 updated_at TIMESTAMP NOT NULL
);
CREATE TABLE users (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 username TEXT NOT NULL,
 username_normalized TEXT NOT NULL UNIQUE,
 password_hash TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
 is_system_admin BOOLEAN NOT NULL DEFAULT FALSE,
 failed_login_count INTEGER NOT NULL DEFAULT 0 CHECK (failed_login_count >= 0),
 locked_until TIMESTAMP,
 password_changed_at TIMESTAMP NOT NULL,
 created_at TIMESTAMP NOT NULL,
 updated_at TIMESTAMP NOT NULL
);
CREATE TABLE organization_members (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL REFERENCES organizations(id),
 user_id BIGINT NOT NULL REFERENCES users(id),
 status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
 created_at TIMESTAMP NOT NULL,
 UNIQUE (organization_id, id),
 UNIQUE (organization_id, user_id)
);
CREATE TABLE roles (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL REFERENCES organizations(id),
 name TEXT NOT NULL,
 description TEXT NOT NULL DEFAULT '',
 is_builtin BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP NOT NULL,
 UNIQUE (organization_id, id),
 UNIQUE (organization_id, name)
);
CREATE TABLE permissions (
 code TEXT NOT NULL PRIMARY KEY,
 description TEXT NOT NULL DEFAULT ''
);
CREATE TABLE role_permissions (
 organization_id BIGINT NOT NULL,
 role_id BIGINT NOT NULL,
 permission_code TEXT NOT NULL REFERENCES permissions(code),
 PRIMARY KEY (organization_id, role_id, permission_code),
 FOREIGN KEY (organization_id, role_id) REFERENCES roles(organization_id, id)
);
CREATE TABLE member_roles (
 organization_id BIGINT NOT NULL,
 member_id BIGINT NOT NULL,
 role_id BIGINT NOT NULL,
 PRIMARY KEY (organization_id, member_id, role_id),
 FOREIGN KEY (organization_id, member_id) REFERENCES organization_members(organization_id, id),
 FOREIGN KEY (organization_id, role_id) REFERENCES roles(organization_id, id)
);
CREATE TABLE user_sessions (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 user_id BIGINT NOT NULL REFERENCES users(id),
 session_hash TEXT NOT NULL UNIQUE,
 csrf_hash TEXT NOT NULL,
 device_summary TEXT NOT NULL DEFAULT '',
 created_at TIMESTAMP NOT NULL,
 expires_at TIMESTAMP NOT NULL,
 revoked_at TIMESTAMP,
 CHECK (expires_at > created_at)
);
CREATE TABLE system_settings (
 setting_key TEXT NOT NULL PRIMARY KEY,
 value_json TEXT NOT NULL,
 version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
 updated_at TIMESTAMP NOT NULL
);
CREATE TABLE providers (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL REFERENCES organizations(id),
 name TEXT NOT NULL,
 description TEXT NOT NULL DEFAULT '',
 contact TEXT NOT NULL DEFAULT '',
 status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
 created_at TIMESTAMP NOT NULL,
 updated_at TIMESTAMP NOT NULL,
 deleted_at TIMESTAMP,
 UNIQUE (organization_id, id)
);
CREATE TABLE model_profiles (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL REFERENCES organizations(id),
 provider_id BIGINT NOT NULL,
 model TEXT NOT NULL,
 display_name TEXT NOT NULL,
 protocol TEXT NOT NULL DEFAULT 'openai_chat',
 capabilities_json TEXT NOT NULL DEFAULT '{}',
 tokenizer_json TEXT NOT NULL DEFAULT '{}',
 public_limits_json TEXT NOT NULL DEFAULT '{}',
 input_price_micros BIGINT CHECK (input_price_micros >= 0),
 output_price_micros BIGINT CHECK (output_price_micros >= 0),
 status TEXT NOT NULL DEFAULT 'active',
 created_at TIMESTAMP NOT NULL,
 updated_at TIMESTAMP NOT NULL,
 deleted_at TIMESTAMP,
 UNIQUE (organization_id, id),
 FOREIGN KEY (organization_id, provider_id) REFERENCES providers(organization_id, id)
);
CREATE TABLE integrity_secrets (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL REFERENCES organizations(id),
 encrypted_data_key BYTEA NOT NULL,
 ciphertext BYTEA NOT NULL,
 nonce BYTEA NOT NULL,
 key_version TEXT NOT NULL,
 payload_key_version TEXT NOT NULL,
 secret_version INTEGER NOT NULL DEFAULT 1 CHECK (secret_version > 0),
 fingerprint TEXT NOT NULL,
 last_four TEXT NOT NULL,
 created_at TIMESTAMP NOT NULL,
 rotated_at TIMESTAMP,
 deleted_at TIMESTAMP,
 UNIQUE (organization_id, id)
);
CREATE TABLE integrity_targets (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL REFERENCES organizations(id),
 provider_id BIGINT,
 model_profile_id BIGINT,
 name TEXT NOT NULL,
 endpoint TEXT NOT NULL,
 endpoint_fingerprint TEXT NOT NULL,
 protocol TEXT NOT NULL DEFAULT 'openai_chat',
 model TEXT NOT NULL,
 auth_type TEXT NOT NULL,
 secret_id BIGINT NOT NULL,
 options_json TEXT NOT NULL DEFAULT '{}',
 status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
 created_by BIGINT NOT NULL,
 updated_by BIGINT NOT NULL,
 created_at TIMESTAMP NOT NULL,
 updated_at TIMESTAMP NOT NULL,
 deleted_at TIMESTAMP,
 UNIQUE (organization_id, id),
 FOREIGN KEY (organization_id, provider_id) REFERENCES providers(organization_id, id),
 FOREIGN KEY (organization_id, model_profile_id) REFERENCES model_profiles(organization_id, id),
 FOREIGN KEY (organization_id, secret_id) REFERENCES integrity_secrets(organization_id, id),
 FOREIGN KEY (organization_id, created_by) REFERENCES organization_members(organization_id, user_id),
 FOREIGN KEY (organization_id, updated_by) REFERENCES organization_members(organization_id, user_id)
);
CREATE TABLE integrity_rule_bundles (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL REFERENCES organizations(id),
 version TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'draft',
 content_hash TEXT NOT NULL,
 content_json TEXT NOT NULL,
 replay_metrics_json TEXT,
 created_by BIGINT NOT NULL,
 created_at TIMESTAMP NOT NULL,
 published_at TIMESTAMP,
 UNIQUE (organization_id, id),
 UNIQUE (organization_id, version),
 FOREIGN KEY (organization_id, created_by) REFERENCES organization_members(organization_id, user_id)
);
CREATE TABLE integrity_template_bundles (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL REFERENCES organizations(id),
 version TEXT NOT NULL,
 sensitivity TEXT NOT NULL,
 content_hash TEXT NOT NULL,
 content_json TEXT NOT NULL,
 created_at TIMESTAMP NOT NULL,
 UNIQUE (organization_id, id),
 UNIQUE (organization_id, version)
);
CREATE TABLE integrity_runs (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL REFERENCES organizations(id),
 target_id BIGINT NOT NULL,
 baseline_run_id BIGINT,
 package TEXT NOT NULL,
 observation_mode TEXT NOT NULL DEFAULT 'blackbox',
 status TEXT NOT NULL,
 config_snapshot TEXT NOT NULL,
 manifest_hash TEXT NOT NULL DEFAULT '',
 rule_bundle_version TEXT NOT NULL,
 template_bundle_version TEXT NOT NULL,
 scoring_version TEXT NOT NULL,
 tokenizer_bundle_version TEXT NOT NULL,
 request_budget BIGINT NOT NULL CHECK (request_budget > 0),
 token_budget BIGINT NOT NULL CHECK (token_budget > 0),
 money_budget_micros BIGINT CHECK (money_budget_micros >= 0),
 request_count BIGINT NOT NULL DEFAULT 0 CHECK (request_count >= 0),
 token_count BIGINT NOT NULL DEFAULT 0 CHECK (token_count >= 0),
 estimated_cost_micros BIGINT NOT NULL DEFAULT 0,
 valid_sample_count INTEGER NOT NULL DEFAULT 0,
 error_summary TEXT,
 lease_owner TEXT,
 lease_until TIMESTAMP,
 cancel_requested_at TIMESTAMP,
 execution_closed_at TIMESTAMP,
 created_by BIGINT NOT NULL,
 created_at TIMESTAMP NOT NULL,
 started_at TIMESTAMP,
 finished_at TIMESTAMP,
 version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
 UNIQUE (organization_id, id),
 FOREIGN KEY (organization_id, target_id) REFERENCES integrity_targets(organization_id, id),
 FOREIGN KEY (organization_id, baseline_run_id) REFERENCES integrity_runs(organization_id, id),
 FOREIGN KEY (organization_id, created_by) REFERENCES organization_members(organization_id, user_id)
);
CREATE TABLE integrity_probe_instances (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL,
 run_id BIGINT NOT NULL,
 probe_type TEXT NOT NULL,
 template_id TEXT NOT NULL,
 template_version TEXT NOT NULL,
 category TEXT NOT NULL,
 variant TEXT NOT NULL,
 planned_samples INTEGER NOT NULL,
 valid_samples INTEGER NOT NULL DEFAULT 0,
 status TEXT NOT NULL,
 parameters_json TEXT NOT NULL,
 result_json TEXT,
 risk_score DOUBLE PRECISION,
 confidence DOUBLE PRECISION,
 evidence_grade TEXT,
 created_at TIMESTAMP NOT NULL,
 finished_at TIMESTAMP,
 UNIQUE (organization_id, id),
 UNIQUE (organization_id, run_id, id),
 FOREIGN KEY (organization_id, run_id) REFERENCES integrity_runs(organization_id, id)
);
CREATE TABLE integrity_logical_samples (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL,
 run_id BIGINT NOT NULL,
 probe_instance_id BIGINT NOT NULL,
 ordinal INTEGER NOT NULL CHECK (ordinal >= 0),
 pair_id TEXT,
 idempotency_key TEXT NOT NULL,
 request_plan TEXT NOT NULL,
 final_attempt_id BIGINT,
 validity TEXT NOT NULL DEFAULT 'PENDING',
 feature_json TEXT,
 rule_result_json TEXT,
 created_at TIMESTAMP NOT NULL,
 completed_at TIMESTAMP,
 UNIQUE (organization_id, id),
 UNIQUE (organization_id, run_id, probe_instance_id, ordinal),
 UNIQUE (organization_id, idempotency_key),
 FOREIGN KEY (organization_id, run_id, probe_instance_id) REFERENCES integrity_probe_instances(organization_id, run_id, id)
);
CREATE TABLE integrity_sample_attempts (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL,
 logical_sample_id BIGINT NOT NULL,
 attempt_no INTEGER NOT NULL CHECK (attempt_no > 0),
 status TEXT NOT NULL DEFAULT 'PLANNED',
 request_snapshot TEXT NOT NULL,
 request_hash TEXT NOT NULL,
 response_meta TEXT NOT NULL DEFAULT '{}',
 response_content_enc BYTEA,
 response_content_redacted TEXT,
 response_hash TEXT,
 response_expires_at TIMESTAMP,
 http_status INTEGER,
 provider_request_id TEXT,
 reported_model TEXT,
 error_code TEXT,
 error_detail TEXT,
 prompt_tokens BIGINT,
 completion_tokens BIGINT,
 total_tokens BIGINT,
 reasoning_tokens BIGINT,
 local_completion_tokens BIGINT,
 tokenizer_id TEXT,
 tokenizer_quality TEXT,
 first_byte_ms BIGINT,
 first_token_ms BIGINT,
 duration_ms BIGINT,
 stream_chunk_count INTEGER NOT NULL DEFAULT 0,
 stream_terminated BOOLEAN,
 billed_estimate_micros BIGINT NOT NULL DEFAULT 0,
 started_at TIMESTAMP,
 finished_at TIMESTAMP,
 UNIQUE (organization_id, id),
 UNIQUE (organization_id, logical_sample_id, id),
 UNIQUE (organization_id, logical_sample_id, attempt_no),
 FOREIGN KEY (organization_id, logical_sample_id) REFERENCES integrity_logical_samples(organization_id, id)
);
CREATE TABLE integrity_run_results (
 organization_id BIGINT NOT NULL,
 run_id BIGINT NOT NULL,
 analysis_revision INTEGER NOT NULL CHECK (analysis_revision > 0),
 prompt_risk DOUBLE PRECISION,
 token_risk DOUBLE PRECISION,
 response_risk DOUBLE PRECISION,
 evidence_risk DOUBLE PRECISION,
 overall_risk DOUBLE PRECISION,
 confidence DOUBLE PRECISION NOT NULL,
 risk_level TEXT NOT NULL,
 evidence_grade TEXT NOT NULL,
 completeness TEXT NOT NULL,
 conclusion_json TEXT NOT NULL,
 is_published BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP NOT NULL,
 PRIMARY KEY (organization_id, run_id, analysis_revision),
 FOREIGN KEY (organization_id, run_id) REFERENCES integrity_runs(organization_id, id)
);
CREATE TABLE integrity_gateway_evidence (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL,
 run_id BIGINT NOT NULL,
 inbound_hash TEXT NOT NULL,
 outbound_hash TEXT NOT NULL,
 changes_json TEXT NOT NULL,
 signature TEXT NOT NULL,
 created_at TIMESTAMP NOT NULL,
 UNIQUE (organization_id, id),
 FOREIGN KEY (organization_id, run_id) REFERENCES integrity_runs(organization_id, id)
);
CREATE TABLE integrity_findings (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL,
 run_id BIGINT NOT NULL,
 analysis_revision INTEGER NOT NULL,
 category TEXT NOT NULL,
 type TEXT NOT NULL,
 severity TEXT NOT NULL,
 risk_score DOUBLE PRECISION NOT NULL,
 confidence DOUBLE PRECISION NOT NULL,
 evidence_grade TEXT NOT NULL,
 title TEXT NOT NULL,
 summary TEXT NOT NULL,
 statistics_json TEXT NOT NULL,
 alternative_explanations TEXT NOT NULL,
 sample_refs TEXT NOT NULL,
 rule_id TEXT NOT NULL,
 rule_version TEXT NOT NULL,
 gateway_evidence_id BIGINT,
 created_at TIMESTAMP NOT NULL,
 UNIQUE (organization_id, id),
 FOREIGN KEY (organization_id, run_id, analysis_revision) REFERENCES integrity_run_results(organization_id, run_id, analysis_revision),
 FOREIGN KEY (organization_id, gateway_evidence_id) REFERENCES integrity_gateway_evidence(organization_id, id)
);
CREATE TABLE integrity_baselines (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL,
 run_id BIGINT NOT NULL,
 analysis_revision INTEGER NOT NULL,
 name TEXT NOT NULL,
 model TEXT NOT NULL,
 protocol TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'pending',
 applicable_scope_json TEXT NOT NULL,
 reviewed_by BIGINT,
 created_at TIMESTAMP NOT NULL,
 reviewed_at TIMESTAMP,
 expires_at TIMESTAMP NOT NULL,
 UNIQUE (organization_id, id),
 FOREIGN KEY (organization_id, run_id, analysis_revision) REFERENCES integrity_run_results(organization_id, run_id, analysis_revision),
 FOREIGN KEY (organization_id, reviewed_by) REFERENCES organization_members(organization_id, user_id)
);
CREATE TABLE integrity_reviews (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL,
 run_id BIGINT NOT NULL,
 analysis_revision INTEGER NOT NULL,
 conclusion TEXT NOT NULL,
 explanation TEXT NOT NULL,
 created_by BIGINT NOT NULL,
 created_at TIMESTAMP NOT NULL,
 UNIQUE (organization_id, id),
 FOREIGN KEY (organization_id, run_id, analysis_revision) REFERENCES integrity_run_results(organization_id, run_id, analysis_revision),
 FOREIGN KEY (organization_id, created_by) REFERENCES organization_members(organization_id, user_id)
);
CREATE TABLE integrity_reports (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL,
 run_id BIGINT NOT NULL,
 analysis_revision INTEGER NOT NULL,
 format TEXT NOT NULL,
 schema_version TEXT NOT NULL,
 revision INTEGER NOT NULL DEFAULT 1,
 content_hash TEXT,
 storage_path TEXT,
 status TEXT NOT NULL,
 error_code TEXT,
 created_at TIMESTAMP NOT NULL,
 completed_at TIMESTAMP,
 UNIQUE (organization_id, id),
 UNIQUE (organization_id, run_id, analysis_revision, format, revision),
 FOREIGN KEY (organization_id, run_id, analysis_revision) REFERENCES integrity_run_results(organization_id, run_id, analysis_revision)
);
CREATE TABLE integrity_audit_chain_heads (
 organization_id BIGINT NOT NULL PRIMARY KEY REFERENCES organizations(id),
 event_count BIGINT NOT NULL DEFAULT 0,
 event_hash TEXT NOT NULL DEFAULT '',
 key_version TEXT NOT NULL,
 updated_at TIMESTAMP NOT NULL
);
CREATE TABLE integrity_audit_logs (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL REFERENCES organizations(id),
 sequence BIGINT NOT NULL,
 actor_id BIGINT,
 action TEXT NOT NULL,
 object_type TEXT NOT NULL,
 object_id TEXT NOT NULL,
 result TEXT NOT NULL,
 ip_summary TEXT NOT NULL,
 user_agent_summary TEXT NOT NULL,
 diff_summary TEXT NOT NULL,
 previous_hash TEXT NOT NULL,
 event_hmac TEXT NOT NULL,
 canonicalization_version TEXT NOT NULL,
 key_version TEXT NOT NULL,
 created_at TIMESTAMP NOT NULL,
 UNIQUE (organization_id, id),
 UNIQUE (organization_id, sequence)
);
CREATE TABLE integrity_audit_segments (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL REFERENCES organizations(id),
 first_sequence BIGINT NOT NULL,
 last_sequence BIGINT NOT NULL,
 first_hash TEXT NOT NULL,
 last_hash TEXT NOT NULL,
 event_count BIGINT NOT NULL,
 first_event_at TIMESTAMP NOT NULL,
 last_event_at TIMESTAMP NOT NULL,
 sealed_at TIMESTAMP NOT NULL,
 canonicalization_version TEXT NOT NULL,
 key_version TEXT NOT NULL,
 deletion_receipt TEXT,
 UNIQUE (organization_id, id),
 UNIQUE (organization_id, first_sequence)
);
CREATE TABLE integrity_jobs (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL REFERENCES organizations(id),
 type TEXT NOT NULL,
 object_id BIGINT NOT NULL,
 idempotency_key TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'completed', 'failed', 'cancelled')),
 priority INTEGER NOT NULL DEFAULT 0,
 available_at TIMESTAMP NOT NULL,
 lease_owner TEXT,
 lease_until TIMESTAMP,
 attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
 max_attempts INTEGER NOT NULL DEFAULT 3 CHECK (max_attempts > 0),
 last_error_code TEXT,
 cancel_requested_at TIMESTAMP,
 created_at TIMESTAMP NOT NULL,
 updated_at TIMESTAMP NOT NULL,
 completed_at TIMESTAMP,
 UNIQUE (organization_id, id),
 UNIQUE (organization_id, idempotency_key)
);
CREATE TABLE integrity_outbox (
 id BIGINT NOT NULL PRIMARY KEY CHECK (id > 0),
 organization_id BIGINT NOT NULL REFERENCES organizations(id),
 event_type TEXT NOT NULL,
 object_id BIGINT NOT NULL,
 idempotency_key TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'pending',
 available_at TIMESTAMP NOT NULL,
 created_at TIMESTAMP NOT NULL,
 delivered_at TIMESTAMP,
 UNIQUE (organization_id, id),
 UNIQUE (organization_id, idempotency_key)
);
