-- v16 used an unnamed composite CHECK. Resolve exactly that immutable shape.
DO $$DECLARE constraint_name text; matches integer; BEGIN SELECT count(*), min(conname::text) INTO matches, constraint_name FROM pg_constraint WHERE conrelid = 'integrity_display_evidence'::regclass AND contype = 'c' AND pg_get_constraintdef(oid) LIKE '%2592000000000%'; IF matches <> 1 THEN RAISE EXCEPTION 'MI_DISPLAY_CONSTRAINT_INVALID'; END IF; EXECUTE format('ALTER TABLE integrity_display_evidence DROP CONSTRAINT %I', constraint_name); END;$$;
ALTER TABLE integrity_display_evidence ADD CONSTRAINT integrity_display_retention_shape CHECK ((state = 'captured' AND length(source_hash) = 64 AND version = 1 AND length(key_version) BETWEEN 1 AND 64 AND nonce IS NOT NULL AND length(nonce) = 12 AND ciphertext IS NOT NULL AND plaintext_bytes BETWEEN 1 AND 4194304 AND length(ciphertext) = plaintext_bytes + 16 AND length(payload_hash) = 64 AND captured_at_micros > 0 AND expires_at_micros > captured_at_micros AND expires_at_micros - captured_at_micros BETWEEN 86400000000 AND 15552000000000 AND (expires_at_micros - captured_at_micros) % 86400000000 = 0) OR (state <> 'captured' AND source_hash = '' AND version = 0 AND key_version = '' AND nonce IS NULL AND ciphertext IS NULL AND plaintext_bytes = 0 AND payload_hash = '' AND captured_at_micros = 0 AND expires_at_micros = 0));
CREATE FUNCTION integrity_run_source_guard() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.analysis_source_version <> OLD.analysis_source_version THEN RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'MI_DERIVED_SOURCE_IMMUTABLE'; END IF; RETURN NEW; END;$$;
CREATE TRIGGER integrity_run_source_immutable BEFORE UPDATE OF analysis_source_version ON integrity_runs FOR EACH ROW EXECUTE FUNCTION integrity_run_source_guard();
CREATE FUNCTION integrity_attempt_source_update_guard() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF (EXISTS (SELECT 1 FROM integrity_runs r WHERE r.organization_id = NEW.organization_id AND r.id = NEW.run_id AND r.analysis_source_version = 'mii.derived-s1.v1') AND NEW.derived_receipt = 'legacy_not_recorded') OR (NOT EXISTS (SELECT 1 FROM integrity_runs r WHERE r.organization_id = NEW.organization_id AND r.id = NEW.run_id AND r.analysis_source_version = 'mii.derived-s1.v1') AND NEW.derived_receipt <> 'legacy_not_recorded') OR (OLD.derived_receipt IN ('derived_recorded','derived_recovered_unavailable') AND NEW.derived_receipt <> OLD.derived_receipt) THEN RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'MI_DERIVED_RECEIPT_INVALID'; END IF; RETURN NEW; END;$$;
CREATE TRIGGER integrity_attempt_source_update BEFORE UPDATE ON integrity_sample_attempts FOR EACH ROW EXECUTE FUNCTION integrity_attempt_source_update_guard();
CREATE FUNCTION integrity_derived_insert_guard_fn() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NOT EXISTS (SELECT 1 FROM integrity_sample_attempts a JOIN integrity_runs r ON r.organization_id = a.organization_id AND r.id = a.run_id WHERE a.organization_id = NEW.organization_id AND a.id = NEW.attempt_id AND a.run_id = NEW.run_id AND a.logical_sample_id = NEW.logical_sample_id AND a.request_hash = NEW.request_hash AND a.status = 'DISPATCHED' AND a.derived_receipt = 'derived_pending' AND r.analysis_source_version = 'mii.derived-s1.v1') THEN RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'MI_DERIVED_SOURCE_INVALID'; END IF; RETURN NEW; END;$$;
CREATE TRIGGER integrity_derived_insert_guard BEFORE INSERT ON integrity_attempt_derived FOR EACH ROW EXECUTE FUNCTION integrity_derived_insert_guard_fn();
CREATE FUNCTION integrity_attempt_derived_guard() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF TG_OP = 'INSERT' THEN IF (EXISTS (SELECT 1 FROM integrity_runs r WHERE r.organization_id = NEW.organization_id AND r.id = NEW.run_id AND r.analysis_source_version = 'mii.derived-s1.v1') AND (NEW.derived_receipt <> 'derived_pending' OR NEW.status <> 'DISPATCHED')) OR (NOT EXISTS (SELECT 1 FROM integrity_runs r WHERE r.organization_id = NEW.organization_id AND r.id = NEW.run_id AND r.analysis_source_version = 'mii.derived-s1.v1') AND NEW.derived_receipt <> 'legacy_not_recorded') THEN RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'MI_DERIVED_RECEIPT_INVALID'; END IF; ELSE IF (OLD.derived_receipt <> 'legacy_not_recorded' AND NEW.derived_receipt = 'legacy_not_recorded') OR (NEW.derived_receipt = 'derived_pending' AND NEW.status <> 'DISPATCHED') OR (NEW.derived_receipt IN ('derived_recorded','derived_recovered_unavailable') AND (NOT EXISTS (SELECT 1 FROM integrity_attempt_derived d WHERE d.organization_id = NEW.organization_id AND d.attempt_id = NEW.id AND d.run_id = NEW.run_id AND d.logical_sample_id = NEW.logical_sample_id AND d.request_hash = NEW.request_hash AND d.status = NEW.status AND d.validity = NEW.validity AND d.error_code = COALESCE(NEW.error_code, '')) OR (NEW.derived_receipt = 'derived_recorded' AND NEW.status <> 'COMPLETED') OR (NEW.derived_receipt = 'derived_recovered_unavailable' AND (NEW.status <> 'UNCERTAIN' OR NEW.validity <> 'INVALID_RETRYABLE' OR COALESCE(NEW.error_code, '') <> 'MI_UNCERTAIN_ATTEMPT')))) THEN RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'MI_DERIVED_RECEIPT_INVALID'; END IF; END IF; RETURN NEW; END;$$;
CREATE TRIGGER integrity_attempt_derived_insert BEFORE INSERT ON integrity_sample_attempts FOR EACH ROW EXECUTE FUNCTION integrity_attempt_derived_guard();
CREATE TRIGGER integrity_attempt_derived_update BEFORE UPDATE ON integrity_sample_attempts FOR EACH ROW EXECUTE FUNCTION integrity_attempt_derived_guard();
