package privatefile

import (
	"context"
	"errors"
	"io"
	"os"
)

// Directory enumeration is a bounded rejection check, never an export source.
func backupWorkspaceNames(dir *os.File, entries map[string]*backupWorkspaceEntry) error {
	seen := make(map[string]bool, len(entries))
	for {
		names, err := dir.Readdirnames(min(100, len(entries)+1-len(seen)))
		for _, name := range names {
			if _, exists := entries[name]; !exists || seen[name] {
				return ErrUnsafe
			}
			seen[name] = true
		}
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return ErrUnavailable
		}
		if len(names) == 0 {
			return ErrUnavailable
		}
	}
	if len(seen) != len(entries) {
		return ErrUnsafe
	}
	return nil
}

func backupWorkspaceInspect(ctx context.Context, native backupWorkspaceNative, entries map[string]*backupWorkspaceEntry, maxBytes int64) error {
	var total int64
	for name, entry := range entries {
		if ctx.Err() != nil {
			return ErrCanceled
		}
		f, err := native.open(name, false)
		if err != nil {
			return err
		}
		err = native.check(f, name, entry.id)
		info, statErr := f.Stat()
		closeErr := f.Close()
		if err != nil {
			return err
		}
		if statErr != nil || closeErr != nil {
			return ErrUnavailable
		}
		if info.Size() < 0 || info.Size() > maxBytes-total {
			return ErrLimit
		}
		if entry.ready && (info.Size() != entry.info.Size || !info.ModTime().Equal(entry.id.ModTime())) {
			return ErrUnsafe
		}
		total += info.Size()
	}
	if ctx.Err() != nil {
		return ErrCanceled
	}
	return nil
}

// Only names generated by this capability are considered. Every removal is
// independently identity-checked; failures retain the private orphan. Unknown
// names and replacement objects are never removed to force cleanup to succeed.
func backupWorkspaceRemoveOwned(native backupWorkspaceNative, entries map[string]*backupWorkspaceEntry) error {
	var first error
	for name, entry := range entries {
		f, err := native.open(name, true)
		if err == nil {
			err = native.check(f, name, entry.id)
			if err == nil {
				err = native.remove(f, name)
			}
			if closeErr := f.Close(); closeErr != nil && err == nil {
				err = ErrUnavailable
			}
		}
		if first == nil {
			first = err
		}
	}
	return first
}
