// Synthetic UI transport fixtures only; never imported by production pages.
import type { Baseline } from '../../baselines-api'
export const org = '9007199254740993', user = '9007199254740995', runID = '9007199254740997', baselineID = '9007199254740999'
export const grants = ['baseline.read', 'baseline.write', 'baseline.approve', 'run.read', 'evidence.read']
export function baselineFixture(patch: Partial<Baseline> = {}): Baseline {
  return { id: baselineID, run_id: runID, target_id: '9007199254740996', analysis_revision: 1, version: 1, name: '组织合成参考', source: 'historical', source_assurance: 'organization_declared_unverified', region: 'declared-r1', region_assurance: 'organization_declared_unverified', model: 'synthetic-model', protocol: 'openai_chat', parameters_hash: 'a'.repeat(64), manifest_hash: 'b'.repeat(64), rule_version: '1.0.0-dev.1', template_version: '1.0.0-dev.1', scoring_version: '1.0.0-dev.1', tokenizer_version: '1.0.0-dev.1', status: 'draft', expected_samples: 60, valid_samples: 60, overall_risk: 41, created_by: user, approved_by: null, created_at: '2026-09-07T10:00:00.000001Z', updated_at: '2026-09-07T10:00:00.000001Z', sampled_at: '2026-09-07T09:00:00Z', approved_at: null, expires_at: new Date(Date.now() + 30 * 86400000).toISOString(), retired_at: null, approval_meaning: 'organization_reviewed_reference_only', development: true, calibrated: false, eligible_for_scoring: false, limitations: ['MI_BASELINE_SOURCE_ORGANIZATION_DECLARED', 'MI_BASELINE_REGION_UNVERIFIED', 'MI_DEVELOPMENT_RULES_UNCALIBRATED', 'MI_PUBLIC_DEVELOPMENT_TEMPLATES', 'MI_BASELINE_SCORING_NOT_ENABLED', 'MI_BASELINE_NOT_APPROVED', 'MI_BASELINE_SOURCE_PARTIAL'], ...patch }
}
export function approvedFixture(current: Baseline): Baseline { return { ...current, version: current.version + 1, status: 'approved', approved_by: user, approved_at: '2026-09-07T11:00:00Z', updated_at: '2026-09-07T11:00:00Z', limitations: current.limitations.filter((code) => code !== 'MI_BASELINE_NOT_APPROVED') } }
export function ok(data: unknown, status = 200) { return Response.json({ data, request_id: 'baseline-test-request' }, { status }) }
export function fail(code: string, status: number) { return Response.json({ error: { code, message: 'PRIVATE_SERVER_BODY' }, request_id: 'baseline-test-error' }, { status }) }
